server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://1xxxxxx.122:3306/spider?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: zxxxxxx
    hikari:
      connection-test-query: SELECT 1 # ??????
      connection-timeout: 60000 #?????????,??30?
      idle-timeout: 500000 #?????????????600000?10???
      max-lifetime: 540000 #??????????????????0???????????1800000?30??
      maximum-pool-size: 12 #????????????10
      minimum-idle: 10 #????????
      pool-name: SPHHikariPool # ?????
